/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemsdevresearchassignment;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author katie.pijohn
 */
public class NewProject extends javax.swing.JFrame {

    DefaultComboBoxModel assignedResearcherModel = new DefaultComboBoxModel();
    DefaultComboBoxModel taskModel = new DefaultComboBoxModel();
    
    
    /**
     * Creates new form NewProject
     */
    public NewProject() {
        initComponents();
        refreshData();
    }
    public void refreshData(){
        try{
         String sqlGetTask = "SELECT id, task FROM tblProjectTasks";
         String sqlGetAssignedResearcher = "SELECT id, assignedResearcher FROM tblProjects";
         
         Connection conn = DBConnection.Connect();
         
         PreparedStatement psGetTask = conn.prepareStatement(sqlGetTask);
         PreparedStatement psGetAssignedResearcher = conn.prepareStatement(sqlGetAssignedResearcher);
         
         ResultSet rs = psGetTask.executeQuery();
         
         this.cmbTask.removeAllItems();
         
         while(rs.next()){
             taskModel.addElement(new ComboBoxItem(rs.getInt("id"), rs.getString("task")));
             
         }
         this.cmbTask.setModel(taskModel);
         
         rs = psGetAssignedResearcher.executeQuery();
         
         this.cmbAssignedResearcher.removeAllItems();
         
         while(rs.next()){
             assignedResearcherModel.addElement(new ComboBoxItem(rs.getInt("id"), rs.getString("assignedResearcher")));
             
         }
         this.cmbAssignedResearcher.setModel(assignedResearcherModel);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Cannot get projects\n\nError" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNewProject = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnBackPage = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblTotalCost = new javax.swing.JLabel();
        lblTask = new javax.swing.JLabel();
        lblAssignedResearcher = new javax.swing.JLabel();
        lblNotes = new javax.swing.JLabel();
        cmbAssignedResearcher = new javax.swing.JComboBox<>();
        cmbTask = new javax.swing.JComboBox<>();
        btnViewProjects = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtName = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTotalCost = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(142, 90, 196));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));

        lblNewProject.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblNewProject.setText("New Project");

        btnCreate.setBackground(new java.awt.Color(235, 197, 246));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBackPage.setBackground(new java.awt.Color(235, 197, 246));
        btnBackPage.setText("Back");
        btnBackPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackPageActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblName.setText("Name");

        lblTotalCost.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblTotalCost.setText("Total Cost");

        lblTask.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblTask.setText("Task");

        lblAssignedResearcher.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblAssignedResearcher.setText("Assigned Researcher");

        lblNotes.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lblNotes.setText("Notes");

        cmbAssignedResearcher.setBackground(new java.awt.Color(235, 197, 246));
        cmbAssignedResearcher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAssignedResearcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAssignedResearcherActionPerformed(evt);
            }
        });

        cmbTask.setBackground(new java.awt.Color(235, 197, 246));
        cmbTask.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnViewProjects.setBackground(new java.awt.Color(235, 197, 246));
        btnViewProjects.setText("View Projects");
        btnViewProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProjectsActionPerformed(evt);
            }
        });

        txtName.setBackground(new java.awt.Color(235, 152, 235));
        txtName.setColumns(20);
        txtName.setRows(5);
        jScrollPane3.setViewportView(txtName);

        txtNote.setBackground(new java.awt.Color(235, 152, 235));
        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane2.setViewportView(txtNote);

        txtTotalCost.setBackground(new java.awt.Color(235, 152, 235));
        txtTotalCost.setColumns(20);
        txtTotalCost.setRows(5);
        jScrollPane4.setViewportView(txtTotalCost);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnViewProjects))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lblNewProject))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotalCost)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTask)
                                    .addComponent(lblAssignedResearcher)
                                    .addComponent(cmbAssignedResearcher, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTask, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNotes)))
                            .addComponent(btnBackPage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackPage)
                    .addComponent(btnViewProjects))
                .addGap(24, 24, 24)
                .addComponent(lblNewProject)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotes)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCost)
                    .addComponent(lblTask))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAssignedResearcher)
                        .addGap(32, 32, 32)
                        .addComponent(cmbAssignedResearcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
  try{
      ComboBoxItem assignedResearcher = (ComboBoxItem)assignedResearcherModel.getSelectedItem();
      ComboBoxItem task = (ComboBoxItem)taskModel.getSelectedItem();
      
      Connection conn = DBConnection.Connect();
      
      String sqlInsert = "INSERT INTO tblProjects(name, totalcost, notes, assignedResearcher) VALUES (?,?,?,?)";
    
      PreparedStatement pStatement = conn.prepareStatement(sqlInsert);
      pStatement.setString(1, this.txtName.getText());
      pStatement.setString(2, this.txtTotalCost.getText());
      pStatement.setString(3, this.txtNote.getText());
      pStatement.setString(4, String.valueOf(assignedResearcher.getId()));
      pStatement.setString(5, String.valueOf(task.getId()));
     
      
      pStatement.executeUpdate();
      JOptionPane.showMessageDialog(null, "Create Successful!\n\nReturning to View Projects screen.");
  }
  catch(Exception e){
      JOptionPane.showMessageDialog(null, "Cannot save project\n\nError" + e);
  }
  ManageProject mp = new ManageProject();
  mp.setVisible(true);
  this.dispose();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void cmbAssignedResearcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAssignedResearcherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAssignedResearcherActionPerformed

    private void btnBackPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackPageActionPerformed
        HeadResearcher am = new HeadResearcher();
        am.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackPageActionPerformed

    private void btnViewProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProjectsActionPerformed
        ManageProject am = new ManageProject();
        am.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewProjectsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackPage;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnViewProjects;
    private javax.swing.JComboBox<String> cmbAssignedResearcher;
    private javax.swing.JComboBox<String> cmbTask;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAssignedResearcher;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNewProject;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblTask;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JTextArea txtName;
    private javax.swing.JTextArea txtNote;
    private javax.swing.JTextArea txtTotalCost;
    // End of variables declaration//GEN-END:variables
}
