/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemsdevresearchassignment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author katie.pijohn
 */
public class ClosedProjects extends javax.swing.JFrame {
    int currentProjects = 0;
    ArrayList<Project> projects = new ArrayList<Project>();
    DefaultComboBoxModel assignedResearcherModel = new DefaultComboBoxModel();

    /**
     * Creates new form ClosedProjects
     */
    public ClosedProjects() {
        initComponents();
        refreshData();
    }
    public void refreshData(){
         try{
            projects.clear();
            
            String sqlGetProjects = "SELECT * FROM tblClosedProjects";
            String sqlGetAssignedResearcher = "SELECT id, assignedResearcher FROM tblClosedProjects";
            
            Connection conn = DBConnection.Connect();
            
            PreparedStatement psGetProjects = conn.prepareStatement(sqlGetProjects);
            PreparedStatement psGetAssignedResearcher = conn.prepareStatement(sqlGetAssignedResearcher);
            
            ResultSet rs = psGetProjects.executeQuery();
            
            while(rs.next()){
                Project p = new Project(rs.getInt("id"), rs.getString("name"), rs.getInt("totalcost"), rs.getString("notes"), rs.getString("assignedResearcher"));
                projects.add(p);
            }
            
            rs = psGetAssignedResearcher.executeQuery();
            
            this.cmbxAssignedResearcher.removeAllItems();
            
            while(rs.next()){
                assignedResearcherModel.addElement(new ComboBoxItem(rs.getInt("id"), rs.getString("assignedResearcher")));
                
                
            }
            for (int i = 0; i < assignedResearcherModel.getSize(); i++){
                ComboBoxItem o = (ComboBoxItem)assignedResearcherModel.getElementAt(i);
                if(o.getId() == projects.get(currentProjects).getId()){
                    assignedResearcherModel.setSelectedItem(o);
                }
                
            
        }
            this.cmbxAssignedResearcher.setModel(assignedResearcherModel);
            this.lblProjectID.setText(String.valueOf(projects.get(currentProjects).getId()));
            this.txtProjectName.setText(projects.get(currentProjects).getName());
            this.txtNotes.setText(projects.get(currentProjects).getNotes());
            this.txtTotalCost.setText(String.valueOf(projects.get(currentProjects).getTotalCost()));
              
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Cannot get Projects!\n\nError"+e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompleteProjects = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblProjectID = new javax.swing.JLabel();
        lblTotalCost = new javax.swing.JLabel();
        lblAssignedResearcher = new javax.swing.JLabel();
        lblNotes = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        txtProjectName = new javax.swing.JTextField();
        txtTotalCost = new javax.swing.JTextField();
        cmbxAssignedResearcher = new javax.swing.JComboBox<>();
        txtNotes = new javax.swing.JTextField();
        lblProjectName = new javax.swing.JLabel();
        btnCloseProject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(142, 90, 196));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));

        lblCompleteProjects.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblCompleteProjects.setText("Complete Projects");

        btnBack.setBackground(new java.awt.Color(235, 197, 246));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblProjectID.setText("Project ID:");

        lblTotalCost.setText("Total Cost:");

        lblAssignedResearcher.setText("Assigned Researcher:");

        lblNotes.setText("Notes:");

        btnPrevious.setText("<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        txtProjectName.setBackground(new java.awt.Color(235, 152, 235));

        txtTotalCost.setBackground(new java.awt.Color(235, 152, 235));
        txtTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCostActionPerformed(evt);
            }
        });

        cmbxAssignedResearcher.setBackground(new java.awt.Color(235, 197, 246));
        cmbxAssignedResearcher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtNotes.setBackground(new java.awt.Color(235, 152, 235));

        lblProjectName.setText("Project Name:");

        btnCloseProject.setBackground(new java.awt.Color(235, 197, 246));
        btnCloseProject.setText("Close Project");
        btnCloseProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNotes)
                            .addComponent(lblAssignedResearcher)
                            .addComponent(lblTotalCost)
                            .addComponent(lblProjectName))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbxAssignedResearcher, javax.swing.GroupLayout.Alignment.LEADING, 0, 139, Short.MAX_VALUE)
                            .addComponent(txtTotalCost, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProjectName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNotes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnFirst)
                        .addGap(24, 24, 24)
                        .addComponent(btnPrevious)
                        .addGap(34, 34, 34)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLast))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(lblCompleteProjects))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(btnCloseProject)))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProjectID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblProjectID))
                .addGap(55, 55, 55)
                .addComponent(lblCompleteProjects)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProjectName))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCost)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssignedResearcher)
                    .addComponent(cmbxAssignedResearcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotes)
                    .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnCloseProject)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnPrevious)
                    .addComponent(btnLast)
                    .addComponent(btnNext))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCostActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnCloseProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseProjectActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to close this project?\n\nThis cannot be undone and will be deleted.", "Warning!", JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION){
            try{
                Connection conn = DBConnection.Connect();
                
                String sqlDelete = "DELETE FROM tblProjects WHERE id=?";
                PreparedStatement pStatement = conn.prepareStatement(sqlDelete);
                pStatement.setString(1, String.valueOf(projects.get(currentProjects).getId()));
                
                pStatement.executeUpdate();
                JOptionPane.showMessageDialog(null, "Project has been closed successfully!");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Cannot close project\n\nError"+ e);
            }
                    currentProjects =0;
                    this.refreshData();
        }
        else{
            JOptionPane.showMessageDialog(null, "Project has not been closed!");
            
        }
    }//GEN-LAST:event_btnCloseProjectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        HeadResearcher hr = new HeadResearcher();
        hr.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClosedProjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClosedProjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClosedProjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClosedProjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClosedProjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCloseProject;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JComboBox<String> cmbxAssignedResearcher;
    private javax.swing.JLabel lblAssignedResearcher;
    private javax.swing.JLabel lblCompleteProjects;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblProjectID;
    private javax.swing.JLabel lblProjectName;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JTextField txtProjectName;
    private javax.swing.JTextField txtTotalCost;
    // End of variables declaration//GEN-END:variables
}
